name: imagined
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.9
  timezone: ^0.9.0
  intl: ^0.18.0
  lottie: ^2.2.0 
  flutter_local_notifications: ^17.2.3
  permission_handler: ^10.2.0
  flutter_datetime_picker: ^1.5.1
  rxdart: ^0.28.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2
 

flutter:
  uses-material-design: true
  assets:
    - assets/animations/logo.png
    - assets/animations/female.json
    - assets/animations/male2.json
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/animations/poppinsFont/Poppins-Regular.ttf
        - asset: assets/animations/poppinsFont/Poppins-Bold.ttf
          weight: 700
flutter_icons:
  android: true
  ios: true
  image_path: "assets/animations/logo.png"
